export { BattlerColorsFormSettings } from './BattlerColorsFormSettings';
export { ArgusFormSettings } from './ArgusFormSettings';
export { FirefliesFormSettings } from './FirefliesFormSettings';
export { ShulteFormSettings } from './ShulteFormSettings';
export { ShiftVerticalFormSettings } from './ShiftVerticalFormSettings';
export { MemoryRhythmFormSettings } from './MemoryRhythmFormSettings';
export { Game2048FormSettings } from './Game2048FormSettings';
export { GameDifferenceFormSettings } from './GameDifferenceFormSettings';
export { SilhouettesFormSettings } from './SilhouettesFormSettings';
export { SteamEngineFormSettings } from './SteamEngineFormSettings';
export { FrazesFormSettings } from './FrazesFormSettings';
export { BullsAndCowsSettings } from './BullsAndCowsSettings';
export type { GamesFormSettingsType } from './game-form-types';
